/**
 * build/icon.ico, the Windows app icon. Generated by scripts/make-icon-ico.mjs because
 * electron-builder's own PNG-to-ICO conversion PNG-compresses every size, and the Windows
 * shell can't read small PNG-compressed icons: the taskbar showed a blank placeholder in
 * 0.4.2 and 0.5.0. e2e/drift.mjs checks the same thing in the built Flowdo.exe.
 */
import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(__dirname, '..')
const ico = readFileSync(join(root, 'build', 'icon.ico'))

const images = Array.from({ length: ico.readUInt16LE(4) }, (_, i) => {
  const e = 6 + i * 16
  const size = ico[e] || 256
  const offset = ico.readUInt32LE(e + 12)
  const data = ico.subarray(offset, offset + ico.readUInt32LE(e + 8))
  return { size, bpp: ico.readUInt16LE(e + 6), data, png: data.subarray(0, 4).toString('latin1') === '\x89PNG' }
})

describe('build/icon.ico', () => {
  it('is an icon file', () => {
    expect(ico.readUInt16LE(0)).toBe(0)
    expect(ico.readUInt16LE(2)).toBe(1)
  })

  it('has every size the taskbar and Explorer ask for', () => {
    const sizes = images.map((i) => i.size)
    for (const s of [16, 20, 24, 32, 40, 48, 64, 256]) expect(sizes).toContain(s)
  })

  it('stores every size below 256 as an uncompressed 32-bit bitmap, never PNG', () => {
    for (const img of images.filter((i) => i.size < 256)) {
      expect(img.png, `${img.size}px`).toBe(false)
      expect(img.bpp).toBe(32)
      expect(img.data.readUInt32LE(0)).toBe(40) // BITMAPINFOHEADER
      expect(img.data.readInt32LE(4)).toBe(img.size)
      expect(img.data.readInt32LE(8)).toBe(img.size * 2) // image plus AND mask
    }
  })

  it('keeps 256x256 as PNG, the one size Windows reads compressed', () => {
    expect(images.find((i) => i.size === 256)?.png).toBe(true)
  })

  it('has real pixels, not a blank image', () => {
    const img = images.find((i) => i.size === 32)!
    const pixels = img.data.subarray(40, 40 + 32 * 32 * 4)
    let opaque = 0
    for (let i = 3; i < pixels.length; i += 4) if (pixels[i]! > 200) opaque++
    expect(opaque).toBeGreaterThan(32 * 32 * 0.5)
  })

  it('is the icon the Windows build uses', () => {
    const config = readFileSync(join(root, 'electron-builder.yml'), 'utf8')
    expect(config).toMatch(/^win:\n(?:\s+#.*\n)*\s+icon: build\/icon\.ico$/m)
  })
})
